apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lzhhuvfx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lzhhuvfx:fcba23f8097ddb9f93af6de3827fbb109542a96c@sha256:449bd7bd57e8532f5869a39b5edfdfe7283bcc617f67b8bcc5ebad0edf0028df
          name: container-image
